An error occurred while executing the following cell:
------------------
X = jax.random.normal(rng, shape=(num_steps, batch_size, len(vocab)))
params = rnn_layer.init(rng, state, X)
state_new, Y = rnn_layer.apply(params, state, X)
Y.shape, state_new.shape
------------------

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
/tmp/ipykernel_1487/2267188814.py in <module>
      1 X = jax.random.normal(rng, shape=(num_steps, batch_size, len(vocab)))
----> 2 params = rnn_layer.init(rng, state, X)
      3 state_new, Y = rnn_layer.apply(params, state, X)
      4 Y.shape, state_new.shape

    [... skipping hidden 12 frame]

~/miniconda3/envs/py37/lib/python3.7/site-packages/flax/core/axes_scan.py in scan_fn(broadcast_in, init, *args)
    133         lu.wrap_init(broadcast_body), in_tree)
    134     in_pvals = list(map(pe.PartialVal.unknown, in_avals))
--> 135     _, out_pvals, _ = pe.trace_to_jaxpr(f_flat, in_pvals)
    136 
    137     out_flat = []

    [... skipping hidden 4 frame]

~/miniconda3/envs/py37/lib/python3.7/site-packages/jax/interpreters/partial_eval.py in tracers_to_jaxpr(in_tracers, out_tracers)
    744       t_to_var[id(t)] = recipe
    745     elif recipe is None:
--> 746       assert False
    747     else:
    748       raise TypeError(recipe)

AssertionError: 
AssertionError: 
